=== SmBe19/LD39/android/assets/cfg/buildings.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://games.smeanox.com"
           xmlns="http://games.smeanox.com"
           elementFormDefault="qualified">
    <xs:element name="buildings">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="building" type="building"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="building">
        <xs:sequence>
            <xs:element name="properties">
                <xs:complexType>
                    <xs:attribute name="width" type="xs:int" use="required"/>
                    <xs:attribute name="height" type="xs:int" use="required"/>
                    <xs:attribute name="dudes_needed" type="xs:int" use="required"/>
                    <xs:attribute name="dudes_capacity_increase" type="xs:int" use="required"/>
                    <xs:attribute name="spaceships_increase" type="xs:int" use="required"/>
                    <xs:attribute name="level_usage" type="xs:float" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="needGridElement">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="element">
                            <xs:complexType>
                                <xs:attribute name="type" type="gridelement" use="required"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="resourcesBuild" type="resourceList"/>
            <xs:element name="resourcesDestroy" type="resourceList"/>
            <xs:element name="resourcesUsage" type="resourceList"/>
        </xs:sequence>
        <xs:attribute name="key" type="xs:string" use="required"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="texture" type="xs:string" use="required"/>
        <xs:attribute name="preview" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:simpleType name="gridelement">
        <xs:restriction base="xs:string">
            <xs:enumeration value="sand"/>
            <xs:enumeration value="water"/>
            <xs:enumeration value="metal"/>
            <xs:enumeration value="oil"/>
            <xs:enumeration value="gas"/>
            <xs:enumeration value="coal"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="resourceList">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="resource">
                <xs:complexType>
                    <xs:attribute name="type" type="resource" use="required"/>
                    <xs:attribute name="amount" type="xs:float" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="resource">
        <xs:restriction base="xs:string">
            <xs:enumeration value="electricity"/>
            <xs:enumeration value="metal"/>
            <xs:enumeration value="propellant"/>
            <xs:enumeration value="water"/>
            <xs:enumeration value="dudes"/>
            <xs:enumeration value="solarpanel"/>
            <xs:enumeration value="oil"/>
            <xs:enumeration value="gas"/>
            <xs:enumeration value="coal"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== SmBe19/LD39/android/assets/cfg/buildings.xml
<?xml version="1.0" encoding="UTF-8" ?>
<buildings xmlns="http://games.smeanox.com"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://games.smeanox.com buildings.xsd">
    <building key="oil">
        <texture id="buildings" x="0" y="0" width="10" height="10"/>
        <properties width="1" height="1" dudes_needed="1" dudes_capacity_increase="0"
                    spaceships_increase="0" level_usage="1"/>
        <needGridElement>
            <element type="oil"/>
        </needGridElement>
        <resourcesBuild>
            <resource type="electricity" amount="5"/>
        </resourcesBuild>
        <resourcesDestroy>
            <resource type="electricity" amount="-5"/>
        </resourcesDestroy>
        <resourceUsage>
            <resource type="electricity" amount="1"/>
            <resource type="gas" amount="1"/>
        </resourceUsage>
    </building>
</buildings>
